[package]
name = "mbr"
version = "0.1.0"
edition = "2021"
workspace = "../../../build"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fzboot = { path = "../../../", features = ["real"] }

[release]
lto = true
opt-level = "z"
