[package]
name = "f-initmbr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flib = { path = "../flib", features = ["real"] }

[release]
lto = true
opt-level = "z"
