[package]
name = "flib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.14"
numtoa = "0.2"
rlibc = "1"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.9"
