name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: cargo-test-x86_64-linux (build)
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        working-directory: ./build
        with:
          command: build
          args: --all --all-features
